#!/bin/bash

while read oldrev newrev refname; do
	repo=`pwd`
	eventId="`date +%s`-`basename $repo`"
	echo "$repo:$refname:$oldrev:$newrev" > /events/$eventId
	echo "Gitomatic event triggered for $repo/$refname. Event id: $eventId"
done