#!/bin/bash

while read oldrev newrev refname; do
	repo=`pwd`
	event="$repo|$refname"
	eventId="`date +%s`-`basename $repo`"
	echo "$repo:$refname" > /events/$eventId
	echo "Gitomatic event triggered for $repo/$refname. Event id: $eventId"
done